
version: 2

sources:
    - name: production
      database: de-course-394517
      schema: hotels_all

      tables:
        - name: hotel_reviews



models:
    - name: prod_hotel_reviews
      description: table with hotel reviews and selected columns
      columns:
        - name: hotelid
          description: unique identifier
          tests:
            - not_null:
                severity: warn

        - name: hotel_name
          description: Name of the hotel.

        - name: hotel_country
          description: Country where the hotel is located.
          tests:
            - not_null:
                config:
                  severity: error
                  error_if: ">14"
                  warn_if: ">11"

        - name: review_date
          description: Date of the review.
          tests:
            - not_null:
                severity: warn

        - name: reviewer_score
          description: Score given by the reviewer.

        - name: average_score
          description: Average score for the hotel.

        - name: hotel_rating
          description: Rating description for the hotel.

        - name: reviewer_nationality
          description: Nationality of the reviewer.



    - name: prod_hotel_reviews_country
      description: table with hotel reviews and selected columns
      columns:
        - name: hotelid
          description: unique identifier
          tests:
            - not_null:
                severity: warn

        - name: hotel_name
          description: Name of the hotel.

        - name: hotel_country
          description: Country where the hotel is located.
          tests:
            - not_null:
                config:
                  severity: error
                  error_if: ">14"
                  warn_if: ">11"

        - name: review_date
          description: Date of the review.
          tests:
            - not_null:
                severity: warn

        - name: reviewer_score
          description: Score given by the reviewer.

        - name: average_score
          description: Average score for the hotel.

        - name: hotel_rating
          description: Rating description for the hotel.

        - name: reviewer_nationality
          description: Nationality of the reviewer.
