name: CI-Tests
on:
  push:
    branches:
      # - main
      - cicd
  pull_request:
    branches:
      # - main
      - cicd
    paths:
      - './**'

env:
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    GCS_REGION: "europe-west6"

jobs:
    authenticate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                version: '442.0.0'  # Specify the desired version of Google Cloud SDK
                service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            - name: Authenticate and use Google Cloud SDK
              run: |
                    gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                    # Set default region for gcloud commands
                    gcloud config set compute/region ${{ env.GCS_REGION }}
                    # Your commands using Google Cloud SDK here

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Python
              run: |
                    conda create -n myenv python=3.9
                    conda activate myenv

            - name: Install dependencies
              working-directory: ./
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Lint
              working-directory: ./
              run: pylint --verbose --recursive=y .
