name: CI-Tests
on:
  push:
    branches:
      # - main
      - cicd
  pull_request:
    branches:
      # - main
      - cicd
    paths:
      - './**'

env:
    GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    GCS_REGION: "europe-west6"
    ACTIONS_STEP_DEBUG: true


jobs:
    authenticate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                version: '442.0.0'  # Specify the desired version of Google Cloud SDK
                service_account_key: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
            - name: Authenticate and use Google Cloud SDK
              run: |
                    gcloud config set project ${{ env.GOOGLE_PROJECT_ID }}
                    gcloud config set compute/region ${{ env.GCS_REGION }}

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set BASE_DIR environment variable
              run: echo "BASE_DIR=/home/runner/work/de-hotel-reviews/de-hotel-reviews" >> $GITHUB_ENV

            - name: Debug Environment Variables
              run: |
                echo "BASE_DIR: $BASE_DIR"

            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9

            - name: Install dependencies
              working-directory: ./
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Lint
              working-directory: ./
              run: pylint --verbose --recursive=y .


    tf-plan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set BASE_DIR environment variable
              run: echo "BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV

            - name: Debug Environment Variables
              run: |
                    echo "BASE_DIR: $BASE_DIR"

            - name: Debug Terraform Directory
              run: |
                ls -l ./terraform

            - name: Configure GCP Credentials
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  version: '442.0.0'  # Specify the desired version of Google Cloud SDK
                  service_account_key: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
            - name: Authenticate and use Google Cloud SDK
              run: |
                    gcloud config set project ${{ env.GOOGLE_PROJECT_ID }}
                    gcloud config set compute/region ${{ env.GCS_REGION }}
            
            - name: Set GOOGLE_APPLICATION_CREDENTIALS for Terraform
              run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/google-credentials.json
              env:
                    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1

            - name: TF Init
              working-directory: 'terraform'
              run: terraform init
              
            - name: TF Plan
              working-directory: 'terraform'
              run: |
                echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/google-credentials.json
                terraform plan -var-file=vars/variables.tfvars
              env:
                GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-credentials.json
            

              
